name: PSGallery

# Controls when the workflow will run
on:
  # Triggers the workflow on new version release
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  psgallery_publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Publish
        run: |
          Publish-Module -Path 'SKYAPI' -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
